// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myyfplvyjpdvcyuyswhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15eWZwbHZ5anBkdmN5dXlzd2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxNzgwNjMsImV4cCI6MjA1MTc1NDA2M30.MSxT6DKzOdx3h4elqR8FEbgBkL3GO-Rp4jTy0Emi_IE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);